### ISSUE TITLE
1.16.3 Crashing On Server and 1.16.4 Latest Version Not Working On Server

### ISSUE THREAD

**Issue by UnfortnatelyAlex** [Corgam/CagedMobs#10]
I made a small modpack for me and my friends on our server, no integration or anything just the plain mods.

On 1.16.3 if the dna sampler has dna in it and is used on the mobcage with the correct terrain it will crash or reload the chunk you were in.

On 1.16.4 if the dna sampler has dna in it and is used on the mobcage with the correct terrain it will not activate and no mob will grow (tested with hay entities and stone entities)

both of these were found true when the mod was by itself as well

**Comment by Corgam** [comment]
I could not reproduce the problem, it should work in the newest version. Please reopen the issue, when you have more information.
