### ISSUE TITLE
1.16.3 Obtaining DNA destroys Off-Hand Items

### ISSUE THREAD

**Issue by SamuelDancing** [Corgam/CagedMobs#11]
When I left click with an item in my Off-hand, and a Diamond syringe (not sure about iron or netherite), it leaves a ghost syringe in the main-hand and replaces the off-hand item with the resulting syringe.

I am playing with other mods, and I will list them for testing in case it's not replicable with just this mod.

Ars Nouveau
Blood Magic
Citadel
Cyclic
Ice and Fire
Industrial Foregoing
Ring of Repair [FORGE]
Titanium
AttributeFix
Better Beacon Placement
Better Burning
Bookshelf
Caelus API (Forge)
Caged Mobs (This mod)
Cloth Config API (Forge)
Collective
Controlling
Curio of Undying (Forge)
Curios API (Forge)
Curious Elytra (Forge)
Dark Utilities
Easy Villagers
GeckoLib
Healing Campfire
Iron Chests
Just Another Rotten Flesh to Leather Mod
JEI
JER
Light Overlay (Rift/Forge/Fabric)
Mineral Chance
MmmMmmMmmMmm
More Dragon Eggs
Mouse Tweaks
No Hostiles Around Campfire
No Nitwits
Patchouli
Placebo
Refined Storage
Refined Storage Addons
Runelic
Solar Flux Reborn
Storage Drawers
Waystones
Wither Skeleton Tweaks

**Comment by Corgam** [comment]
I could not reproduce the problem, it should work in the newest version. Please reopen the issue, when you have more information.
