### ISSUE TITLE
CraftTweaker Additional Loot Import Invalid

### ISSUE THREAD

**Issue by zachsai** [Corgam/CagedMobs#14]
It seems that the 
"       import mods.cagedmobs.CTAdditionalLoot;
    val additionalLoots = <recipetype:cagedmobs:additional_loot_data>;"
is invalid. I am using all three (entity, environment, loot) the only one not working is loot. It says so in the chat when I reload

**Comment by Corgam** [comment]
Oh, I forgot to update the wiki. I changed it to "AdditionalLoot" only.
Try: "import mods.cagedmobs.AdditionalLoot;"
