### ISSUE TITLE
Render Errors

### ISSUE THREAD

**Issue by InkDragon** [Corgam/CagedMobs#15]
i seem to be getting errors like this:

> at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
> [11:17:25] [Render thread/ERROR] [co.co.ca.CagedMobs/]: Error getting cached entity!
> java.lang.NullPointerException: null

i'd have posted the full log but it was nearly 2gb...

please feel free to ask any questions and I can try to generate a smaller log to show off the issue if need be

**Comment by skruis** [comment]
I'm getting a similar error and my logfile was huge as well:

[Render thread/ERROR] [com.corgam.cagedmobs.CagedMobs/]: Error getting cached entity!
java.lang.NullPointerException: null
	at com.corgam.cagedmobs.tileEntities.MobCageTE.getCachedEntity(MobCageTE.java:82) ~[cagedmobs:1.16.4-1.2.6]
	at com.corgam.cagedmobs.tileEntities.MobCageRenderer.render(MobCageRenderer.java:54) ~[cagedmobs:1.16.4-1.2.6]
	at com.corgam.cagedmobs.tileEntities.MobCageRenderer.func_225616_a_(MobCageRenderer.java:32) ~[cagedmobs:1.16.4-1.2.6]

Forge: 35.1.13
Java: 1.8.0_242 by AdoptOpenJDK
Launcher: GDLauncher

I was using these in the hopper variant on top of Storage Drawers. I had roughly 10 of these setup and my FPS dropped from 180 to 30. There were: sheep, iron golem and a cow.

**Comment by Corgam** [comment]
Sorry for that! It should be working properly in the next version!
