### ISSUE TITLE
Hopping Mob Cages Stuck at 100%

### ISSUE THREAD

**Issue by fFIRE332A** [Corgam/CagedMobs#16]
When using your mod in tandem with the Not Enough Wands Moving Wand item, caged will get stuck at 100% rather than dumping into a chest.

**Comment by Corgam** [comment]
I have decided I will not fix it. By default, it is not possible to move the cage, so I would not use Not Enough Wands to move the cage. If you want to move the cage, one other mod adds card boxes, and as far as I know, they can move cages perfectly.
