### ISSUE TITLE
Entities Not Displaying In Cages

### ISSUE THREAD

**Issue by fFIRE332A** [Corgam/CagedMobs#17]
Within multiplayer servers the entities do not display within the cages, it worked in the same modpack in single player. Upon using the cages in multiplayer entities are no longer visible in their cages, so I assume it has something to do with multiplayer.

**Comment by RedCubeDev-ByteSpace** [comment]
Yeah this issue is still a thing
My friend and I were trying out mods on a Server and thought it was completely busted
After some time i found this thread. It works fine in Singleplayer
Please fix this!

**Comment by Corgam** [comment]
Sorry for a long wait! It should be working properly in the next version!
