### ISSUE TITLE
Request: Loot support for Craft and Hunt

### ISSUE THREAD

**Issue by Subnova7** [Corgam/CagedMobs#18]
As title says, I would like to request loot support for [Craft and Hunt](https://www.curseforge.com/minecraft/mc-mods/craft-and-hunt). Things like the various hides, chitins, and meats added by the mod, including the ability to sample other vanilla mobs like foxes, bats, etc.

**Comment by Corgam** [comment]
There are too many items to be added, I will leave it to someone who wants to make a datapack for it ;)
