### ISSUE TITLE
Crash while looking at ice&fire Recipe in JEI

### ISSUE THREAD

**Issue by BluMasc** [Corgam/CagedMobs#2]
The game crashes when trying to load some of the ice and fire mobs. I think they are doing something weird with rendering.

Maybe you could implement something that catches NullPointerExceptions and just renders nothing instead?

Pastebin: [https://pastebin.pl/view/67262950](url)

**Comment by Corgam** [comment]
Did you create your own json file for ice and fire entity?

**Comment by BluMasc** [comment]
Yes. Here is the file.
[amphithere.txt](https://github.com/Corgam/CagedMobs/files/5494403/amphithere.txt)

Changed to txt for upload purposes

**Comment by Corgam** [comment]
There is a bigger problem with rendering Ice and Fire entities. Maybe I will solve it near future, for now unfortunately most of I&F entities probably won't work.

**Comment by Corgam** [comment]
I looked into it. When NullPointerExceptions is catched, the RenderSystem already did some calculations. Even if we catch the exception it's really hard to revert already made changes and render no entity model. I will look into it again in the future, but for now IceAndFire won't be supported.

**Comment by BluMasc** [comment]
OK, still thanks for your effort.

Additionally to anyone who looks at this. Most Ice and Fire mobs work, the ones who caused problems for me where these:

- all Myrmex Kinds
- the Sea Serpent
- the Amphithere
- the Siren

Also i didn't try the death worm or any of the dread creatures.

**Comment by Corgam** [comment]
I have added support for Fire and Ice, it will be up in the next update. All mobs are working except the Amphithere and I have no idea why, thus it is the only mob which will not be able to be sampled.
