### ISSUE TITLE
Wither Skeletons not dropping skulls

### ISSUE THREAD

**Issue by Mr404ServerError** [Corgam/CagedMobs#21]
Minecraft Version: 1.16.4
Forge Version: 35.1.13
Mod Version: cagedmobs-1.16.4-1.2.6

When harvesting Wither Skeletons, the "Wither skeleton skull" item in never dropped, only bones and coal.
When wither skeletons are killed normally in the world, they do drop the skulls

**Comment by Corgam** [comment]
Did you upgrade your cage with the lightning upgrade?

**Comment by Mr404ServerError** [comment]
Ah, that has started the Skull drop. I thought that wither could drop heads normally though, not just from a charged creeper explosion. 

Problem solved for now though. Thanks!
