### ISSUE TITLE
Crafttweaker added mob do not show text and picture in multiplayer + entities in cage do not show growing in multiplayer

### ISSUE THREAD

**Issue by zachsai** [Corgam/CagedMobs#22]
Why does the mob inside not show when on a server? Also, the mob picture and name does not show when looking at what the cage can produce for mobs that were added with craft tweaker.
![image](https://user-images.githubusercontent.com/63996164/104395048-e0da2900-5515-11eb-8271-f11f4f18ff1a.png)
 the Ender Golem and Titan text + pictures do not show in multiplayer, making it where players dont know what entity they need to hit with dna picker to get the drop
also, entities do not render in multiplayer, why is that?
1.16.4, latest version

**Comment by Corgam** [comment]
Sorry for that! It should be working properly in the next version!
