### ISSUE TITLE
!Urgent! Modpack becomes unplayable after 15/20 mins of playing, lag spikes every 0.5 seconds

### ISSUE THREAD

**Issue by zachsai** [Corgam/CagedMobs#23]
https://gist.github.com/celsiusqc/1fa3028e196e92b9f43dc4493a281dcc

Without optifine, problem goes away.
With optifine the problem occurs. 
The support team at optifine pointed towards your mod after being provided this debug.log
Hopefully you can fix this soon.

**Comment by Corgam** [comment]
Sorry for long wait! Should be fixed in the next version!
