### ISSUE TITLE
Offhand Items get deleted

### ISSUE THREAD

**Issue by ItsDarry** [Corgam/CagedMobs#24]
For some reason, if you have an item in your offhand and use the syringe, it'll delete that item and replace it with another syringe. Lost two shields doing this.

**Comment by Omni35** [comment]
Can confirm that this happens. The offhand items get voided and in its place appears a ghost syringe. Tried with all 3 samplers, on cats, cows, sheep, and pigs, lost a few shields (both vanilla and modded ones from Tetra) and stacks of torches. Doesn't happen every time, about 1/3 times. Playing the Odisea modpack.

**Comment by Corgam** [comment]
Should be fixed in the next version.
