### ISSUE TITLE
Request/Suggestion: Blacklist/Whitelist mob drops for caged mobs

### ISSUE THREAD

**Issue by VallenFrostweaver** [Corgam/CagedMobs#25]
I would love love love to use this mod in my pack - but - it can be a bit strong and nullify a lot of other mods being able to produce the drops of so many critters. I greatly appreciate the ability to turn off the hopping version. Adding in a blacklist or whitelist of mobs to allow or disallow (or even all) would be great. This would allow me to still have a farm for one resource but not that precious other one they need to quest for. Or just being able to turn off all the drops still allows the use of the aesthetic beauty of these models in a pack. Thanks for the mod and I hope you consider my request/suggestion. <3

**Comment by Corgam** [comment]
Thanks for the ideas! I implemented the ability to turn off the hopping cage in the next version. More will come in the future!

**Comment by Corgam** [comment]
A blacklist (or whitelist) for entities inside server config has been added in the latest update. In the next update I'm also planning to make a blacklist for specific items. Also ability to turn off hopping version was added before :)

**Comment by Corgam** [comment]
A blacklist/whitelist for individual items will be added in the next update. Thanks for the ideas!
