### ISSUE TITLE
Crash when putting entity in cage

### ISSUE THREAD

**Issue by BluMasc** [Corgam/CagedMobs#3]
When i rightclick a cage with a dna sampler the game crashes with this error:  [https://pastebin.com/tq42CAaa](url)

**Comment by BluMasc** [comment]
Also a similar error also occurs while hovering over the data sampler.

**Comment by Corgam** [comment]
I hope I can fix it in next version. Can you tell me which entity did you hit with the DNA Sampler?

**Comment by BluMasc** [comment]
Ohh, totaly forgot. I fisrt tried with a stoneling from quark. And then with a normal minecraft zombie. Game crashed in both instances.

**Comment by Corgam** [comment]
That's strange. Was it possible to sample the stoneling? Did you add your own json file? When I try to reproduce the bug, when I hit the stoneling it says "Cannot sample this type of entity". I hope it will be fixed in next version.

**Comment by BluMasc** [comment]
yes i made my own json. This one: 
[stoneling.txt](https://github.com/Corgam/CagedMobs/files/5495205/stoneling.txt)
