### ISSUE TITLE
[Enhancement] Future supported mods and datapack database

### ISSUE THREAD

**Issue by pwigary** [Corgam/CagedMobs#31]
Hey, I'm sorry if there is any reason this isn't a thing yet.. It seems like the mod is still adding support for another mod in the recent update. So, could we possibly get a list of other mods that this mod will probably have a support to? It would be really helpful. like really, for modpackers. :) Even the list shows "none".

**Comment by Corgam** [comment]
Hi,
thanks for the idea, I don't have a list of mods that I want to support in the future, but instead from time to time I'm just looking at the comments and on Curse Forge by myself and then deciding which mod I want to support.  
Right now I now that I will try to make a support for "Craft and hunt", we will see how it will turn out. 
Also from the beginning I wanted to add a support for Twilight Forest when it's updated to the newest version of Minecraft.

When it comes to the place where everyone can put their datapack, it's a cool idea. I'm not sure where that would be for now, but I can think about it. Feel free to write any ideas that you have.

EDIT: I just saw that Twilight Forest is updated to 1.16.5, I will work on it in the next version of my mod. Also I think I will add support to Better Animals Plus.

**Comment by pwigary** [comment]
Neat~ Twilight Forest mod support would be very good. And Alex's mob is also very good in 1.16!

More mods in 1.16 that add good mobs (for reference):

1. [Alex's Mob](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs/screenshots)
2. [Outvote](https://www.curseforge.com/minecraft/mc-mods/outvoted)
3. [Mowzie's Mobs](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs)
4. [Mutant Beasts](https://www.curseforge.com/minecraft/mc-mods/mutant-beasts/screenshots)
5. [Creatures and Beasts](https://www.curseforge.com/minecraft/mc-mods/creatures-and-beasts/screenshots)
6. [Odd Water Mobs](https://www.curseforge.com/minecraft/mc-mods/odd-water-mobs)

**Comment by pwigary** [comment]
I'm not too familiar with Github, but Discord will probably best for sharing I suppose. Could also encourage people to PM in the mod page for some resource, maybe.

**Comment by Corgam** [comment]
Few days ago I have created a Discord server: https://discord.com/invite/V4ezDH45SZ
All datapacks, feedback and bugs can be shared there. Thank you for ideas :)
