### ISSUE TITLE
Server crashing on launch

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Corgam/CagedMobs#32]
Just updated to the latest version and getting this crash. Looks like the mod is trying to pickup some client features while running on a server

[crash-2021-05-09_11.23.57-fml.txt](https://github.com/Corgam/CagedMobs/files/6447295/crash-2021-05-09_11.23.57-fml.txt)

**Comment by Corgam** [comment]
I hope it will be fixed in the quick updated I will roll out in a moment, please let me know.
