### ISSUE TITLE
Caged mobs crashing server

### ISSUE THREAD

**Issue by grandogarndo** [Corgam/CagedMobs#33]
This mods looks awesome, but it crashes my dedicated server
log: https://pastebin.com/iDrsK28q

**Comment by grandogarndo** [comment]
I'm pretty sure I'm using the newest version, but I will download the newest one and try again.

**Comment by Corgam** [comment]
Hi, as far as I can see you are using an old version 1.3.3, try using the 1.3.4 which should fix the issue.

**Comment by Corgam** [comment]
I heard from other people that this bug was fixed in the latest version of Caged Mobs, please reopen this issue if you still have problems.
