### ISSUE TITLE
Request/Suggestion:I tried to make zh_cn.lang for this mod

### ISSUE THREAD

**Issue by 6371peter** [Corgam/CagedMobs#34]
Hi,I am using your mod for the game.This is a very convenient mod,and I noticed that this mod does not have zh_cn.lang.So I took the en_us.lang in the mod as a sample for translation.
[zh_cn.zip](https://github.com/Corgam/CagedMobs/files/6792594/zh_cn.zip)

**Comment by ZCLDAYEDE** [comment]
wow~~找一下还找到了汉化~nice兄嘚~

**Comment by Corgam** [comment]
Hi, sorry for not responding for so long, I will work on the mod in the following weeks and I will take a look at your translation. Thank you!

**Comment by Corgam** [comment]
Hi, I will add your translation in the next update, thanks!
