### ISSUE TITLE
Request: Grottols from Mowzie's mobs require stone and diamond ore to spawn instead of wheat and grass

### ISSUE THREAD

**Issue by warning-djkajslh** [Corgam/CagedMobs#35]
I want to bring up a special mob in this thread, that is Grottols from Mowzie's Mobs. Grottols are passive typed mobs that spawn naturally in diamond levels, their design consist of diamonds growing from them, plus, they drop diamonds and burry themself into stone or dirt if possible. Therefore, their matching spawning block should be stone or diamond ores instead, not only that will fit with the mob's lore, but it will also raise the spawing requirement for a mob with such as overpowered drop.

**Comment by Corgam** [comment]
As far as I can see, the Grottols already need a stone block or diamond ore to be used in cages.

**Comment by warning-djkajslh** [comment]
Oh, was worrying since Mowzie changed the Grottol to from being a hostile into a passive mob a while back.
