### ISSUE TITLE
Slime Cage

### ISSUE THREAD

**Issue by ArrowFX** [Corgam/CagedMobs#38]
Hi! I just wanted to tell you Corgam that the slime cage(And possibly others) have mismatched blocks in JEI or it's some other programming problem. 

Problem: In the JEI Menu it says that one of the two environments for slimes is "Stone" but when you place Stone in the cage and then try to add Slime DNA it says that it isn't a suitable environment.

**Comment by Corgam** [comment]
Hi, thank you, which version of Caged Mobs and Minecraft are you using?

**Comment by ArrowFX** [comment]
> 
> 
> Hi, thank you, which version of Caged Mobs and Minecraft are you using?

cagedmobs-1.16.5-1.3.7.jar and well... forge 1.16.5 (36.2.0)

**Comment by Corgam** [comment]
And by any chance do you have installed Tinkers Construct? If yes, did you sample the slime from one of their islands?

**Comment by ArrowFX** [comment]
> ance do you have installed Tinkers Construct? If yes, did you sample the slime from one of their islands?

Yes, I did, Is it a compatibility problem? And if it is sry that I wasted your time.

**Comment by Corgam** [comment]
It's not a problem, but there is one catch: there are vanilla Minecraft slimes and Tinkers Construct slimes, they look the same and have the same name, but I made it that the ones from Tinkers require slime blocks from Tinkers as an environment. I will tweak that, so all slimes can use both environments so nobody is confused, thanks!
