### ISSUE TITLE
Cannot register the Grottol's DNA from Mowzie's 

### ISSUE THREAD

**Issue by warning-djkajslh** [Corgam/CagedMobs#41]
The mod has it so you can only deal damage to the mob with a pickaxe, since you need to damage the mob for the sampler to register, this make Grottols unregistable even in Creative.

**Comment by Corgam** [comment]
Makes sense. Unfortunately, I could either delete Grottols from being sampled or make the samplers as pickaxes (Would be strange, but maybe it won't break other things...). I will think about it later.

**Comment by warning-djkajslh** [comment]
Making the samplers as pickaxe would actually game breaking, you can now mine stones with the samplers.
Other note, the only way to damage the grottol is to punch them with an iron pick, and even if they take one swing, they will flop and dies no matter how much damage was dealt to it, so now you can kill Grottols with samplers.

**Comment by Mdbgamer** [comment]
To be fair, simply taking a Grottal sample would be kinda gamebreaking. I mean, pretty much guaranteed diamonds, yaknow? And if you're using samplers to mine stone, then ya must be desperate or something. x)

I wonder if the Mowzie's dev could add some kind of config for adding exceptions for the Grottal when it comes to what can damage it...

**Comment by MCCrafter247** [comment]
Another solution could be that if the sampler is in the offhand while something takes damage from whatever you're holding in the main hand, it could also count. That way you could hold a pickaxe in the main hand, and the sampler in the off-hand. It would fix any possible mobs that need a specific tool to damage them.

**Comment by Mdbgamer** [comment]
Coming back after an eon and my laptop dying, started digging through Github to find anything I forgot about, and found this and my post on the Mowzies github. The dev added a method to add weapons that can damage the Grottal. Datapacks, I think.

**Comment by Corgam** [comment]
It turns out that Mowzie's Mob Author added Caged Mobs compatability themself :)
