### ISSUE TITLE
Datapack support : Removing loot to existing entities

### ISSUE THREAD

**Issue by fori00** [Corgam/CagedMobs#43]
Hello, 
Have you planned to add the possibility of deleting loot by datapack?
In the same way as the addition (cagedmobs:additional_loot_data)
So something like (cagedmobs:remove_loot_data)

Thank you for your work

**Comment by Corgam** [comment]
Thanks for the suggestion, implemented in the last code push. There is now an optional `removeFromEntity` field in the additional loot data JSON objects.
