### ISSUE TITLE
Bug: Caged mobs and environment block disappearing when login in an out of world

### ISSUE THREAD

**Issue by jeannemas** [Corgam/CagedMobs#44]
As the title say: when I log out of a world, the mob cages are emptied, and I loose both the mob and the environment block.

Caged Mobs version: `1.18.1-1.5.0`
Forge version: `39.0.9`
Minecraft version: `1.18.1`

[See video for proof](https://user-images.githubusercontent.com/24734881/148309690-6a623696-bb90-4071-9979-26266e774059.mp4)

![Screenshot from 2022-01-05 19-36-56](https://user-images.githubusercontent.com/24734881/148309762-994f9da8-d201-4bb7-9e09-13b20c39cd7a.png)
![Screenshot from 2022-01-05 19-39-26](https://user-images.githubusercontent.com/24734881/148309763-d19ff46a-148a-47e7-ab26-758e8ff0350f.png)

**Comment by Corgam** [comment]
Thank you for creating the issue, I will look into it in the following days.

**Comment by jeannemas** [comment]
As a quick update, it seems that the problem is with the hopping cage since after a logout/login, after clearing it's inventory because of the bug, the hopping cage (if not broken and then replaced), behaves just like a normal cage, it does not output the loot automatically, it requires a right-click (just like the normal cage). It is fixed by breaking and placing it again.

**Comment by trogarus** [comment]
I have the same issue with the hopping cages not maintaining information on world reload in single player. For now, will try breaking and replacing to see if that at least gets me things back.

Minecraft 1-18-1
Forge 39.0.19
cagedmobs-1.18.1-1.5.0

**Comment by trogarus** [comment]
Looks like last update fixed my issue. Thanks.
