### ISSUE TITLE
[Bug] Items do not generate/drop

### ISSUE THREAD

**Issue by itsdinkd** [Corgam/CagedMobs#46]
Using latest 1.5.1 in my modpack, AQM3, Caged Mobs do not drop any items in hopper cage or regular cage. Have placed chests underneath, nothing. have tried numerous entities, nothing. 

I went on your discord and saw people said to "Break it and replace it" to which I have, still nothing. All that did was reset the cage to not have a entity in it, and give me back the block used for the environment.

**Comment by Corgam** [comment]
Unfortunatelly, I do not have enough information to help you, on my side everything seems working fine. If this situation happens in the newest updates comming soon (a lot will be changed), please repost this bug :)

**Comment by itsdinkd** [comment]
Almost 2 years later lol.

**Comment by Corgam** [comment]
Well, a lot to do in the meantime, but I am happy to be updating the mod once again! :)
