### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by ZEROX7** [Corgam/CagedMobs#52]
Forge 40.1.59
[crash-2022-07-26_11.48.59-fml.txt](https://github.com/Corgam/CagedMobs/files/9188659/crash-2022-07-26_11.48.59-fml.txt)

**Comment by Corgam** [comment]
Thank you for the submission, however, 1.18.2 was not fully supported. I have just bumped the version number by one from 1.18.1, without testing or changing anything. I might revisit this version tho, so if this bug still occurs after future updates, please report it once again.
EDIT: Additionally, unfortunately the crash log is not descriptive enough for me to fix anything
