### ISSUE TITLE
"Permission" conflicts with LGPL

### ISSUE THREAD

**Issue by NoaHimesaka1873** [Corgam/CagedMobs#53]
Per LGPL, the recipient is allowed to redistribute binaries. But, your permissions contain "You are allowed to repost Caged Mobs only when the download link redirects to the CurseForge page," which conflicts with LGPL allowing to redistribute the binary. Please remove that line of text. (You of course can't stop licensing this as LGPL.)

**Comment by Corgam** [comment]
Correct, I will change it. However, one still needs to disclose the source and state the changes :)
