### ISSUE TITLE
Conflicts with aternos server hosting

### ISSUE THREAD

**Issue by DeformedEggo** [Corgam/CagedMobs#54]
Aternos states that, 
 "The author of this project does not allow project distribution."
When attempting to add the mod to the site in order to add the mod to servers.

**Comment by Corgam** [comment]
After some thinking, I have decided to allow the distribution of this project outside the CurseForge ecosystem. Happy playing! 
However, it might take a while for the CurseForge database to update the status.

**Comment by DeformedEggo** [comment]
Thank you very much!
