### ISSUE TITLE
Forge 47.1.43 crash when loading JEI 1.20.1

### ISSUE THREAD

**Issue by iinstincts** [Corgam/CagedMobs#55]
Crash when loading JEI in-game
using a lot of mods so if you can't fix the conflict no worries :)

[crash-2023-11-01_16.40.56-client.txt](https://github.com/Corgam/CagedMobs/files/13231650/crash-2023-11-01_16.40.56-client.txt)

**Comment by Corgam** [comment]
Thank you for your report, the problem was there because of some mods interfering with each other. I cannot strictly fix it so it works properly, but I hopefully made it so that it will not crash anymore, instead it will not render the problematic entity.
