### ISSUE TITLE
Bug: Possible recipe tag/nbt incompatility

### ISSUE THREAD

**Issue by kurtramone** [Corgam/CagedMobs#56]
Hello. Trying to craft Fortune upgrade, an it seems to not be working, don't know but I guess a mod is modifying vanilla Fortune III book:

Trying to craft
![Captura de tela 2023-11-09 233015](https://github.com/Corgam/CagedMobs/assets/55619656/0712289a-2f76-4902-8bad-d4e8fc24d741)
![Captura de tela 2023-11-09 233033](https://github.com/Corgam/CagedMobs/assets/55619656/9a72cec6-3717-4617-9485-7de0d89fd241)

Recipe in JEI
![Captura de tela 2023-11-09 233101](https://github.com/Corgam/CagedMobs/assets/55619656/fcdd5fe1-d3af-445f-8b24-5ecd31c6c653)
![Captura de tela 2023-11-09 233049](https://github.com/Corgam/CagedMobs/assets/55619656/26f7c9a4-e424-43d4-9ab4-a7e200ee2716)

MC: 1.19.2
Forge: 43.3.2
Mod: 2.0.0

By the way, this recipe shouldn't be using Loot III?

**Comment by Corgam** [comment]
Thank you for your report, after some thought I have decided to change the recipe of the upgrade, so it does not require an enchanted book. It is not worth the hassle to try to get it working with other mods loaded. Finally, I think you are correct, I have renamed the upgrade to a "Looting Upgrade" :)

**Comment by kurtramone** [comment]
Glad to help, really like your mod
