### ISSUE TITLE
Remove "Speed Upgrade" when progress bar is full, then mobs are buggy

### ISSUE THREAD

**Issue by qznfbnj** [Corgam/CagedMobs#58]
After removing the "Speed Upgrade" when the progress bar is full, mobs in the cage cannot be harvested by right-clicking with sword, and they will no longer grow. The only solution is to put back the "Speed Upgrade" and let the progress bar reach 100%.
## Mod List
Forge_43.3.2

![image](https://github.com/Corgam/CagedMobs/assets/100760086/a08f84ef-d68a-415b-8097-f49ef13a4538)
## Remove Speed III Cage Upgrade
![image](https://github.com/Corgam/CagedMobs/assets/100760086/035064c3-6a22-4781-a2f6-06c6fb35f7ef)
## Remove Speed II Cage Upgrade
![image](https://github.com/Corgam/CagedMobs/assets/100760086/59d8e4c4-9120-4f4c-b7c5-3c2386bb61ff)

**Comment by Corgam** [comment]
Thank you for the report, I will take a look at it soon!

**Comment by Corgam** [comment]
Thank you, I will backport the change to previous versions soon.
