### ISSUE TITLE
MC Server 1.16.4 - Error connecting to world

### ISSUE THREAD

**Issue by MachinegunMarty** [Corgam/CagedMobs#7]
[2020-11-10-1.log](https://github.com/Corgam/CagedMobs/files/5517121/2020-11-10-1.log)
cagedmobs-1.16.4-1.2.3.jar
forge-1.16.4-35.0.7.jar

Started a new server yesterday with cagedmobs-1.16.4-1.2.2.jar.
Today i did my Mod update check and downloaded: cagedmobs-1.16.4-1.2.3.jar.
Server and client start with no problems.
When trying to connect to the server it gives this message:

Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Failed to read mob data from packetbuffer. This is really bad.

I can only go back to the server listing.

I downloaded a couple of updates of mods so i tested by adding them one by one and this one pops up the error.
Going back to cagedmobs-1.16.4-1.2.2.jar on server and client fixes the error and i can log in again.

**Comment by Corgam** [comment]
I could not reproduce the problem, I hope it will work in the newest version. Please reopen the issue, when you have more information.
