### ISSUE TITLE
Config options to change environmental blocks for custom modpacks?

### ISSUE THREAD

**Issue by Dragnier** [Corgam/CagedMobs#8]
As the title says, could you add some way to configure the environmental blocks for specific entities and maybe even another config to whitelist or blacklist entities from being used?

**Comment by Corgam** [comment]
In the next version there will be CraftTweaker support, it will definitely help to edit existing recipes. When it comes to the possibility to blacklist some entities I will do it in the future.

**Comment by Corgam** [comment]
TODO: Blacklist for entities

**Comment by Corgam** [comment]
A blacklist (or whitelist) for entities inside server config has been added in the latest update.
