### ISSUE TITLE
Cages do not accept Hay Bale

### ISSUE THREAD

**Issue by erandisvol** [Corgam/CagedMobs#9]
The regular cage and the hopper cage do not accept the hay bale block. Regular clicking and shift-clicking make no difference. Instead, the hay bale is placed as a block next to the cage.

This has been tested in 1.16.3 with Forge 34.1.25 using the mod version 1.2.3  and no other mods installed.

**Comment by willrun4fun** [comment]
I am also having this issue.  1.16.3 and Forge 34.1.42

**Comment by willrun4fun** [comment]
[mods.txt](https://github.com/Corgam/CagedMobs/files/5542351/mods.txt)
Here is my mods list

**Comment by Corgam** [comment]
I was testing new environments and I accidentally changed hay bale into grass block in the recipe. It will change back into hay bale in next version.

**Comment by Corgam** [comment]
Should be fixed in 1.2.4. If not create a new issue.

**Comment by willrun4fun** [comment]
I had a chance to test it today.  Working great!
